In [40]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,ID,date,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,R00210,2010-11-11,121.05,121.82,120.68,121.64,157659616.0,1.14,52.90,53.480,...,71.48,69.4500,71.07,279282.0,2.0300,137.6200,137.75,136.45,137.66,15380502.0
1,R03365,2023-05-26,415.33,420.77,415.25,420.02,93829975.0,5.52,340.76,349.245,...,133.61,131.3700,131.37,20046.0,2.2400,181.0100,181.30,180.09,180.92,5823674.0
2,R03382,2023-06-22,433.95,436.62,433.60,436.51,70637175.0,3.02,360.63,366.330,...,122.23,116.9100,118.86,74797.0,5.3200,178.3600,178.99,177.63,177.71,7948565.0
3,R01294,2015-03-06,210.46,210.46,207.10,207.50,188127982.0,3.36,108.50,108.710,...,79.73,79.0500,79.28,60988.0,0.6800,113.1700,113.26,111.70,111.86,11190846.0
4,R02502,2019-12-20,320.46,321.97,319.39,320.73,149214080.0,2.58,211.86,212.520,...,182.57,172.1033,173.79,88426.0,10.4667,139.3705,139.52,138.98,139.52,4446611.0

In [41]:
#preprocessing

cols_imputing = ['us_rates_%', 'CPI', 'usd_chf', 'eur_usd', 'GDP']

for col in cols_imputing:
    df_train[col] = df_train[col].fillna(df_train[col].mean())
    df_test[col] = df_test[col].fillna(df_train[col].mean())

df_train.head()

,ID,date,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,...,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold close,gold volume
0,R00210,2010-11-11,121.05,121.82,120.68,121.64,157659616.0,1.14,52.90,53.480,...,71.48,69.4500,71.07,279282.0,2.0300,137.6200,137.75,136.45,137.66,15380502.0
1,R03365,2023-05-26,415.33,420.77,415.25,420.02,93829975.0,5.52,340.76,349.245,...,133.61,131.3700,131.37,20046.0,2.2400,181.0100,181.30,180.09,180.92,5823674.0
2,R03382,2023-06-22,433.95,436.62,433.60,436.51,70637175.0,3.02,360.63,366.330,...,122.23,116.9100,118.86,74797.0,5.3200,178.3600,178.99,177.63,177.71,7948565.0
3,R01294,2015-03-06,210.46,210.46,207.10,207.50,188127982.0,3.36,108.50,108.710,...,79.73,79.0500,79.28,60988.0,0.6800,113.1700,113.26,111.70,111.86,11190846.0
4,R02502,2019-12-20,320.46,321.97,319.39,320.73,149214080.0,2.58,211.86,212.520,...,182.57,172.1033,173.79,88426.0,10.4667,139.3705,139.52,138.98,139.52,4446611.0

In [42]:
df_train.columns

Index(['ID', 'date', 'sp500 open', 'sp500 high', 'sp500 low', 'sp500 close',
       'sp500 volume', 'sp500 high-low', 'nasdaq open', 'nasdaq high',
       'nasdaq low', 'nasdaq close', 'nasdaq volume', 'nasdaq high-low',
       'us_rates_%', 'CPI', 'usd_chf', 'eur_usd', 'GDP', 'silver open',
       'silver high', 'silver low', 'silver close', 'silver volume',
       'silver high-low', 'oil open', 'oil high', 'oil low', 'oil close',
       'oil volume', 'oil high-low', 'platinum open', 'platinum high',
       'platinum low', 'platinum close', 'platinum volume',
       'platinum high-low', 'palladium open', 'palladium high',
       'palladium low', 'palladium close', 'palladium volume',
       'palladium high-low', 'gold open', 'gold high', 'gold low',
       'gold close', 'gold volume'],
      dtype='object')

In [43]:
features = ['sp500 open', 'sp500 high', 'sp500 low', 'sp500 close', 'sp500 volume', 'sp500 high-low', 'nasdaq open', 'nasdaq high', 'nasdaq low', 'nasdaq close', 'nasdaq volume', 'nasdaq high-low',
       'us_rates_%', 'CPI', 'usd_chf', 'eur_usd', 'GDP', 'silver open', 'silver high', 'silver low', 'silver close', 'silver volume', 'silver high-low', 'oil open', 'oil high', 'oil low', 'oil close',
       'oil volume', 'oil high-low', 'platinum open', 'platinum high', 'platinum low', 'platinum close', 'platinum volume', 'platinum high-low', 'palladium open', 'palladium high',
       'palladium low', 'palladium close', 'palladium volume', 'palladium high-low', 'gold open', 'gold high', 'gold low', 'gold volume']
target = 'gold close'

X = df_train[features]
y = df_train[target]
X_final = df_test[features]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=features)
X_final = pd.DataFrame(scaler.transform(X_final), columns=features)

X.head()

,sp500 open,sp500 high,sp500 low,sp500 close,sp500 volume,sp500 high-low,nasdaq open,nasdaq high,nasdaq low,nasdaq close,...,palladium open,palladium high,palladium low,palladium close,palladium volume,palladium high-low,gold open,gold high,gold low,gold volume
0,-1.231835,-1.230755,-1.228852,-1.226778,0.665520,-0.709965,-1.058755,-1.056573,-1.057957,-1.054751,...,-0.659716,-0.666800,-0.681667,-0.663470,2.215883,-0.091354,-0.258573,-0.274575,-0.276475,0.918222
1,1.214111,1.240494,1.233299,1.252031,-0.259609,0.955681,1.308212,1.356951,1.329537,1.369959,...,0.405957,0.404447,0.416585,0.390446,-0.527092,-0.011501,1.221269,1.203064,1.220855,-0.604841
2,1.368873,1.371516,1.386677,1.389022,-0.595759,0.004970,1.471596,1.496369,1.491688,1.516010,...,0.229160,0.208232,0.160113,0.171798,0.052228,1.159689,1.130889,1.124686,1.136450,-0.266199
3,-0.488692,-0.498019,-0.506514,-0.513491,1.107120,0.134267,-0.601577,-0.605881,-0.606323,-0.610723,...,-0.521838,-0.524554,-0.511395,-0.519977,-0.093884,-0.604701,-1.092455,-1.105513,-1.125671,0.250520
4,0.425587,0.423771,0.432057,0.427173,0.543113,-0.162355,0.248315,0.241237,0.256906,0.246512,...,1.282266,1.248616,1.139056,1.131858,0.196437,3.116755,-0.198871,-0.214519,-0.189668,-0.824302

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from lightgbm import LGBMRegressor
from sklearn.model_selection import cross_val_score

model = LinearRegression()

cross_val_score(model, X, y, cv=5, scoring='neg_root_mean_squared_error')

array([-0.28039898, -0.28650251, -0.34680883, -0.26919722, -0.26485057])

In [45]:
model.fit(X, y)
y_final = model.predict(X_final)

In [46]:
submission = pd.DataFrame({
    "ID": df_test.ID,
    "gold close": y_final
})

submission

         ID  gold close
0    R00904  132.371320
1    R03254  165.530163
2    R01784  116.865385
3    R01972  121.185415
4    R02105  123.593651
..      ...         ...
739  R01235  118.345173
740  R01453  111.633462
741  R02639  169.422271
742  R02686  183.540702
743  R03593  215.679046

[744 rows x 2 columns]

In [47]:
submission.to_csv("submission.csv", index=False)