In [30]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,SampleID,solar_irradiance,temperature,humidity,wind_speed,cloud_cover,panel_angle,panel_efficiency,energy_output
0,1,624.724071,27.840633,18.249910,1.689351,70.723863,15.553988,20.307842,32.52
1,2,970.428584,16.682799,82.204233,2.785903,15.253904,26.257028,15.172108,65.91
2,3,839.196365,18.232574,50.420190,1.770105,57.628836,36.188375,15.154865,32.53
3,4,759.195091,32.971084,76.116597,0.887025,60.671505,31.966747,17.265272,27.09
4,5,493.611184,27.128581,35.603968,1.206359,42.413067,34.196834,18.420502,35.60

In [31]:
df_train.columns

Index(['SampleID', 'solar_irradiance', 'temperature', 'humidity', 'wind_speed',
       'cloud_cover', 'panel_angle', 'panel_efficiency', 'energy_output'],
      dtype='object')

In [32]:
features = ['solar_irradiance', 'temperature', 'humidity', 'wind_speed', 'cloud_cover', 'panel_angle', 'panel_efficiency']
target = 'energy_output'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=features)
X_final = pd.DataFrame(scaler.transform(X_final), columns=features)

X.head()

,solar_irradiance,temperature,humidity,wind_speed,cloud_cover,panel_angle,panel_efficiency
0,-0.372140,0.470994,-1.362137,-1.113971,0.856519,-1.184865,0.917536
1,1.586615,-1.437843,1.245778,-0.719721,-1.092404,-0.005786,-1.610140
2,0.843056,-1.172714,-0.050305,-1.084937,0.396428,1.088281,-1.618627
3,0.389770,1.348691,0.997537,-1.402435,0.503332,0.623214,-0.579939
4,-1.115023,0.349180,-0.654477,-1.287624,-0.138174,0.868887,-0.011364

In [33]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

len(X_train)

160

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import root_mean_squared_error

model = LinearRegression().fit(X, y)
y_preds = model.predict(X_valid)
root_mean_squared_error(y_valid, y_preds)

9.72722884405545

In [35]:
y_final = model.predict(X_final)

In [36]:
submission = pd.DataFrame({
    "SampleID": df_test.SampleID,
    "energy_output": y_final
})

submission.head()

   SampleID  energy_output
0         1      70.064720
1         2      46.081435
2         3      58.430194
3         4      70.564431
4         5      91.286398

In [37]:
submission.to_csv("submission.csv", index=False)