In [81]:
import pandas as pd

df = pd.read_csv("muzee.csv")

df.head()

,_id,codul entității muzeale,identificatorul înregistrării,județul,denumirea (română),denumirea cu localitate (română),denumirea (engleză),denumirea cu localitate (engleză),localitatea,unitatea administrativă,...,codul LMI al clădirii,codul SIRUTA al localității,data ultimei modificări,profilul principal (engleză),ordinul de acreditare,categoria (română),categoria (engleză),latitudine,longitudine,coordonatele
0,1,7083504,8,București,"Muzeul Memorial ""Dr. Victor Babeș""","Muzeul Memorial ""Dr. Victor Babeș"" - BUCUREȘTI",Dr. Victor Babeș Memorial Museum,Dr. Victor Babeș Memorial Museum - BUCHAREST,BUCUREȘTI,NaN,...,B-II-m-B-19267,179141.0,30.09.2013 12:50:47,Memorials -,NaN,Muzeu municipal,City museum,"44,460065","26,091329",muzeu
1,2,7300205,9,București,"Muzeul de Artă Veche Apuseană ""ing. Dumitru Mi...","Muzeul de Artă Veche Apuseană ""ing. Dumitru Mi...",Eng. Dumitru Minovici Western Old Art Museum,Eng. Dumitru Minovici Western Old Art Museum -...,BUCUREȘTI,NaN,...,B-II-m-A-19206,179141.0,05.12.2013 11:37:34,NaN,NaN,Muzeu în subordinea Academiei Române,Museum under the Romanian Academy,"44,484256","26,074651",muzeu
2,3,7084103,10,București,"Colecția de Artă Plastică ""Fr. Storck și Cecil...","Colecția de Artă Plastică ""Fr. și Cecilia Cuțe...",Fr. Storck and Cecilia Cuțescu Storck Fine Art...,Fr. Storck and Cecilia Cuțescu Storck Fine Art...,BUCUREȘTI,NaN,...,B-II-m-B-18332,179141.0,05.12.2013 11:37:34,NaN,NaN,Muzeu municipal,City museum,"44,450912","26,094471",muzeu
3,4,7300407,12,București,"Casa Memorială ""George și Agatha Bacovia""","Casa Memorială ""George și Agatha Bacovia"" - BU...",George and Agatha Bacovia Memorial House,George and Agatha Bacovia Memorial House - BUC...,BUCUREȘTI,NaN,...,NaN,179178.0,03.10.2013 16:08:28,NaN,NaN,Muzeu municipal,City museum,"44,397006","26,101241",muzeu
4,5,7300402,13,București,"Muzeul Memorial ""George Călinescu""","Muzeul Memorial ""George Călinescu"" - BUCUREȘTI",George Călinescu Memorial Museum,George Călinescu Memorial Museum - BUCHAREST,BUCUREȘTI,NaN,...,B-II-m-B-18411,179141.0,30.09.2013 12:50:47,NaN,NaN,Muzeu în subordinea Academiei Române,Museum under the Romanian Academy,"44,462162","26,099546",muzeu

In [82]:
#subtaskurile
subtask1 = len(df)
subtask2 = len(df[df["județul"] == "București"])
subtask3 = (df.isna().sum() >= 1).sum()
subtask4 = df['anul înființării'].value_counts().index[0]

df_1 = pd.DataFrame({
    "id": [1, 2, 3, 4],
    "subtaskID": [1, 2, 3, 4],
    "answer": [subtask1, subtask2, subtask3, subtask4]
})

df_1

   id  subtaskID answer
0   1          1   1008
1   2          2     59
2   3          3     33
3   4          4   2006

In [83]:
subtask5 = df["județul"].value_counts()

df_2 = pd.DataFrame({
    "id": subtask5.index,
    "subtaskID": 5,
    "answer": subtask5.values
})

df_2.head()

          id  subtaskID  answer
0       Alba          5      60
1  București          5      59
2      Sibiu          5      47
3      Neamț          5      43
4    Prahova          5      41

In [84]:
def scor_completitudine(row):
    nr_na = row.isna().sum()
    nr_bune = (len(df.columns) - nr_na)
    nr_total = len(df.columns)
    scor = nr_bune / nr_total * 100
    return scor

subtask6 = df.apply(scor_completitudine, axis=1)

df_3 = pd.DataFrame({
    "id": df._id,
    "subtaskID": 6,
    "answer": subtask6
})

df_3.head()

   id  subtaskID     answer
0   1          6  81.818182
1   2          6  81.818182
2   3          6  77.272727
3   4          6  79.545455
4   5          6  65.909091

In [88]:
subtask7 = subtask6.mean()

nr_cu_com_max = len(subtask6[subtask6 == subtask6.max()])
subtask8 = nr_cu_com_max / len(df) * 100

df_4 = pd.DataFrame({
    "id": [7, 8],
    "subtaskID": [7, 8],
    "answer": [subtask7, subtask8]
})

df_4

   id  subtaskID     answer
0   7          7  72.585227
1   8          8   1.488095

In [89]:
submission = pd.concat([df_1, df_2, df_3, df_4])
submission

        id  subtaskID     answer
0        1          1       1008
1        2          2         59
2        3          3         33
3        4          4       2006
0     Alba          5         60
...    ...        ...        ...
1005  1008          6  72.727273
1006  1009          6  61.363636
1007  1011          6  79.545455
0        7          7  72.585227
1        8          8   1.488095

[1056 rows x 3 columns]

In [90]:
submission.to_csv("submission.csv", index=False)