In [1]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_train.head()

,User_ID,Age,Height,Weight,Duration,Heart_Rate,Body_Temp,Gender,Calories
0,14498311,79,165,73,13,79,40.0,male,54
1,16700865,28,148,48,6,91,39.4,female,28
2,17197650,27,187,82,25,101,40.8,male,128
3,16400540,40,173,71,16,93,40.4,male,69
4,15539631,40,183,90,5,80,39.0,male,14

In [2]:
subtask_1 = len(df_train)
subtask_2 = len(df_train[df_train.Gender == 'male'])
subtask_3 = df_train.Duration.mean()
subtask_4 = len(df_train[df_train.Age >= 75])

subtasks = pd.DataFrame({
    "subtaskID": [1, 2, 3, 4],
    "datapointID": 1,
    "answer": [subtask_1, subtask_2, subtask_3, subtask_4]
})

subtasks

   subtaskID  datapointID       answer
0          1            1  9000.000000
1          2            1  4443.000000
2          3            1    15.510667
3          4            1   412.000000

In [3]:
df_train.Gender = df_train.Gender.map({"male": 0, "female": 1})
df_test.Gender = df_test.Gender.map({"male": 0, "female": 1})

df_test.Gender = df_test.Gender.fillna(df_test.Gender.mean())

features = ['Age', 'Height', 'Weight', 'Duration', 'Heart_Rate', 'Body_Temp', 'Gender']
target = 'Calories'

X = df_train[features]
y = df_train[target]

X_final = df_test[df_test.Subtask == 5]
X_final  = X_final[features]

X.head()

   Age  Height  Weight  Duration  Heart_Rate  Body_Temp  Gender
0   79     165      73        13          79       40.0       0
1   28     148      48         6          91       39.4       1
2   27     187      82        25         101       40.8       0
3   40     173      71        16          93       40.4       0
4   40     183      90         5          80       39.0       0

In [4]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)
y_final = model.predict(X_final)

In [5]:
subtask_5 = pd.DataFrame({
    "subtaskID": 5,
    "datapointID": df_test[df_test.Subtask == 5].User_ID,
    "answer": y_final
})

subtask_5.head()

   subtaskID  datapointID      answer
0          5     12618012  110.165559
1          5     19091177  132.008535
2          5     14793975  106.002969
3          5     17338539  156.220090
4          5     16351902    3.800352

In [6]:
submission = pd.concat([subtasks, subtask_5])
submission

      subtaskID  datapointID       answer
0             1            1  9000.000000
1             2            1  4443.000000
2             3            1    15.510667
3             4            1   412.000000
0             5     12618012   110.165559
...         ...          ...          ...
1995          5     16551300   195.852852
1996          5     19031605    63.540835
1997          5     10044742   183.570713
1998          5     17921022   170.411536
1999          5     19414695   111.877527

[2004 rows x 3 columns]

In [7]:
submission.to_csv("submission.csv", index=False)