In [2]:
import pandas as pd

df_train = pd.read_csv("train_iris.csv")
df_test = pd.read_csv("test_iris.csv")

df_train.head()

,sepal_length_(cm),sepal_width_(cm),petal_length_(cm),petal_width_(cm),target,SampleID
0,4.4,2.9,1.4,0.2,0,9
1,4.9,2.5,4.5,1.7,2,107
2,6.8,2.8,4.8,1.4,1,77
3,4.9,3.1,1.5,0.1,0,10
4,5.5,2.5,4.0,1.3,1,90

In [3]:
df_train.columns

Index(['sepal_length_(cm)', 'sepal_width_(cm)', 'petal_length_(cm)',
       'petal_width_(cm)', 'target', 'SampleID'],
      dtype='object')

In [4]:
features = ['sepal_length_(cm)', 'sepal_width_(cm)', 'petal_length_(cm)', 'petal_width_(cm)']
target = 'target'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

X.head()

   sepal_length_(cm)  sepal_width_(cm)  petal_length_(cm)  petal_width_(cm)
0                4.4               2.9                1.4               0.2
1                4.9               2.5                4.5               1.7
2                6.8               2.8                4.8               1.4
3                4.9               3.1                1.5               0.1
4                5.5               2.5                4.0               1.3

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

model = KNeighborsClassifier(n_neighbors=3)

cross_val_score(model, X, y, cv=3, scoring='f1_macro')

array([0.94871795, 0.95054945, 1.        ])

In [29]:
model.fit(X, y)
y_final = model.predict(X_final)

In [30]:
submission = pd.DataFrame({
    "SampleID": df_test.SampleID,
    "label": y_final
})

submission.head()

   SampleID  label
0        39      0
1       128      2
2        58      1
3        94      1
4        43      0

In [31]:
submission.to_csv("submission.csv", index=False)