In [20]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,SampleID,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,...,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,2276,18,95,Low,High,No,7,96,Medium,Yes,...,Medium,High,Private,Positive,4,Yes,High School,Moderate,Male,70
1,4604,16,89,High,Medium,Yes,8,58,Low,Yes,...,Low,Medium,Public,Neutral,3,No,College,Moderate,Male,67
2,2203,16,69,Medium,High,Yes,6,55,Medium,Yes,...,Medium,High,Public,Negative,1,No,High School,Moderate,Male,62
3,472,11,65,Medium,High,No,7,78,Medium,Yes,...,Low,Medium,Public,Neutral,3,No,Postgraduate,Near,Female,63
4,4061,21,95,Medium,High,Yes,8,57,Low,No,...,Low,Medium,Public,Positive,3,No,High School,Near,Male,69

In [21]:
to_encode = ["Parental_Involvement", "Access_to_Resources", "Extracurricular_Activities", "Motivation_Level", "Internet_Access", "Family_Income", "Teacher_Quality", "School_Type", "Peer_Influence", "Learning_Disabilities", "Parental_Education_Level", "Distance_from_Home", "Gender"]

categories = [
    ["Low", "Medium", "High"],                    # Parental_Involvement
    ["Low", "Medium", "High"],                    # Access_to_Resources
    ["No", "Yes"],                                # Extracurricular_Activities
    ["Low", "Medium", "High"],                    # Motivation_Level
    ["No", "Yes"],                                # Internet_Access
    ["Low", "Medium", "High"],                    # Family_Income
    ["Low", "Medium", "High"],                    # Teacher_Quality
    ["Public", "Private"],                        # School_Type
    ["Negative", "Neutral", "Positive"],         # Peer_Influence
    ["No", "Yes"],                                # Learning_Disabilities
    ["High School", "College", "Postgraduate"],  # Parental_Education_Level
    ["Near", "Moderate", "Far"],                  # Distance_from_Home
    ["Male", "Female"]                            # Gender
]

from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder(categories=categories)

df_train[to_encode] = enc.fit_transform(df_train[to_encode])
df_test[to_encode] = enc.transform(df_test[to_encode])

df_train.head()

,SampleID,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,...,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,2276,18,95,0.0,2.0,0.0,7,96,1.0,1.0,...,1.0,2.0,1.0,2.0,4,1.0,0.0,1.0,0.0,70
1,4604,16,89,2.0,1.0,1.0,8,58,0.0,1.0,...,0.0,1.0,0.0,1.0,3,0.0,1.0,1.0,0.0,67
2,2203,16,69,1.0,2.0,1.0,6,55,1.0,1.0,...,1.0,2.0,0.0,0.0,1,0.0,0.0,1.0,0.0,62
3,472,11,65,1.0,2.0,0.0,7,78,1.0,1.0,...,0.0,1.0,0.0,1.0,3,0.0,2.0,0.0,1.0,63
4,4061,21,95,1.0,2.0,1.0,8,57,0.0,0.0,...,0.0,1.0,0.0,2.0,3,0.0,0.0,0.0,0.0,69

In [22]:
df_train.columns

Index(['SampleID', 'Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [23]:
features = ['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender']

target = 'Exam_Score'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

len(X_train)

4081

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

model = LinearRegression().fit(X, y)
y_preds = model.predict(X_valid)
root_mean_squared_error(y_valid, y_preds)

2.437265230718618

In [29]:
y_final = model.predict(X_final)

In [30]:
submission = pd.DataFrame({
    "SampleID": df_test.SampleID,
    "Exam_Score": y_final
})

submission

      SampleID  Exam_Score
0         2719   73.859982
1         4276   66.105317
2         4142   70.453896
3         1200   72.077866
4         4547   67.412768
...        ...         ...
1271      6012   68.686770
1272      5295   64.882940
1273      4906   62.947564
1274      6279   67.084173
1275      2639   73.704193

[1276 rows x 2 columns]

In [31]:
submission.to_csv("submission.csv", index=False)