In [12]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_train.head()

,ID,date,home_team,away_team,neutral,tournament,tourn_weight,is_world_cup,is_qualifier,is_friendly,...,h2h_away_win_rate,h2h_draw_rate,home_penalty_reliance,away_penalty_reliance,home_owngoal_benefit_rate,away_owngoal_benefit_rate,home_shootout_win_rate,away_shootout_win_rate,true_home_advantage,result
0,0,1872-11-30,Scotland,England,0,Friendly,20,0,0,1,...,0.330000,0.340000,0.0,0.0,0.0,0.0,0.5,0.5,1,D
1,1,1873-03-08,England,Scotland,0,Friendly,20,0,0,1,...,0.000000,1.000000,0.0,0.0,0.0,0.0,0.5,0.5,1,H
2,2,1874-03-07,Scotland,England,0,Friendly,20,0,0,1,...,0.500000,0.500000,0.0,0.0,0.0,0.0,0.5,0.5,1,H
3,3,1875-03-06,England,Scotland,0,Friendly,20,0,0,1,...,0.333333,0.333333,0.0,0.0,0.0,0.0,0.5,0.5,1,D
4,4,1876-03-04,Scotland,England,0,Friendly,20,0,0,1,...,0.250000,0.500000,0.0,0.0,0.0,0.0,0.5,0.5,1,H

In [13]:
years = df_train.date.apply(lambda x : x[:4])
sb1 = years.mode()[0]

df_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": [0],
    "answer": sb1
})

df_1

   subtaskID  datapointID answer
0          1            0   2011

In [14]:
feats = [col for col in df_train.columns if df_train[col].dtype != 'str' and col != 'ID']
target = 'result'

X = df_train[feats]
y = df_train[target]

X_final = df_test[feats]

X.head()

,neutral,tourn_weight,is_world_cup,is_qualifier,is_friendly,same_confederation,elo_home,elo_away,elo_diff,elo_expected_home,...,h2h_home_win_rate,h2h_away_win_rate,h2h_draw_rate,home_penalty_reliance,away_penalty_reliance,home_owngoal_benefit_rate,away_owngoal_benefit_rate,home_shootout_win_rate,away_shootout_win_rate,true_home_advantage
0,0,20,0,0,1,1,1500.000000,1500.000000,0.000000,0.500000,...,0.330000,0.330000,0.340000,0.0,0.0,0.0,0.0,0.5,0.5,1
1,0,20,0,0,1,1,1500.000000,1500.000000,0.000000,0.500000,...,0.000000,0.000000,1.000000,0.0,0.0,0.0,0.0,0.5,0.5,1
2,0,20,0,0,1,1,1491.760408,1508.239592,-16.479184,0.476302,...,0.000000,0.500000,0.500000,0.0,0.0,0.0,0.0,0.5,0.5,1
3,0,20,0,0,1,1,1502.835081,1497.164919,5.670163,0.508159,...,0.333333,0.333333,0.333333,0.0,0.0,0.0,0.0,0.5,0.5,1
4,0,20,0,0,1,1,1497.287308,1502.712692,-5.425384,0.492193,...,0.250000,0.250000,0.500000,0.0,0.0,0.0,0.0,0.5,0.5,1

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model = RandomForestClassifier()

#cross_val_score(model, X, y, cv=3, scoring='accuracy')

In [16]:
model.fit(X, y)
y_preds = model.predict(X_final)

In [17]:
df_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.ID,
    "answer": y_preds
})

df_2.head()

   subtaskID  datapointID answer
0          2        39275      H
1          2        39276      H
2          2        39277      A
3          2        39278      A
4          2        39279      A

In [18]:
submission = pd.concat([df_1, df_2])
submission

      subtaskID  datapointID answer
0             1            0   2011
0             2        39275      H
1             2        39276      H
2             2        39277      A
3             2        39278      A
...         ...          ...    ...
9814          2        49089      A
9815          2        49090      A
9816          2        49091      A
9817          2        49092      A
9818          2        49093      A

[9820 rows x 3 columns]

In [19]:
submission.to_csv("submission.csv", index=False)