In [69]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_train.head()

,AppID,Name,Release date,Estimated owners,Price,Metacritic score,Recommendations,Positive,Negative,Publishers,Genres
0,350110,TransOcean 2: Rivals,"May 10, 2016",100000 - 200000,29.99,69,428,305,281,astragon Entertainment,"Simulation,Strategy"
1,312780,Way of the Samurai 4,"July 23, 2015",200000 - 500000,24.99,72,1475,1288,318,"Spike Chunsoft Co., Ltd.","Action,Adventure"
2,230150,Incredipede,"March 18, 2013",50000 - 100000,9.99,74,140,243,96,Northway Games,"Action,Adventure,Casual,Indie,Simulation"
3,1252300,RetroMania Wrestling,"February 25, 2021",0 - 20000,29.99,66,174,211,30,Retrosoft Studios,"Action,Sports"
4,760650,Hammerting,"November 16, 2021",100000 - 200000,9.99,64,1358,1328,705,Team17 Digital,"Adventure,Indie,RPG,Simulation,Strategy"

In [70]:
#subtask1

def get_owners(value):
    minmax = value.split(' - ')
    media = (int(minmax[0]) + int(minmax[1])) / 2
    return media

df_test['Estimated owners'] = df_test['Estimated owners'].apply(get_owners)
df_train['Estimated owners'] = df_train['Estimated owners'].apply(get_owners)

subtask1 = pd.DataFrame({"subtaskID":1, "datapointID": df_test.AppID, "answer": df_test['Estimated owners']})

subtask1.head()

   subtaskID  datapointID    answer
0          1       636230   10000.0
1          1       256460  150000.0
2          1       327890  750000.0
3          1       287020   75000.0
4          1        25980  350000.0

In [71]:
#preprocess- uhhhhhhh
def get_year(value):
    return int(value.split(', ')[1])

df_test['Release date'] = df_test['Release date'].apply(get_year)
df_train['Release date'] = df_train['Release date'].apply(get_year)

features = ['Release date', 'Estimated owners', 'Metacritic score', 'Recommendations', 'Positive', 'Negative']
target = 'Price'

X = df_train[features]
y = df_train[target]
X_final = df_test[features]

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
scaled_X = pd.DataFrame(scaled_X, columns=features)
scaled_X_final = scaler.transform(X_final)
scaled_X_final = pd.DataFrame(scaled_X_final, columns=features)

scaled_X

,Release date,Estimated owners,Metacritic score,Recommendations,Positive,Negative
0,0.692308,0.004286,0.636364,0.000546,0.000316,0.002163
1,0.653846,0.010000,0.675325,0.001883,0.001335,0.002448
2,0.576923,0.002143,0.701299,0.000179,0.000252,0.000739
3,0.884615,0.000286,0.597403,0.000222,0.000219,0.000231
4,0.884615,0.004286,0.571429,0.001733,0.001376,0.005426
...,...,...,...,...,...,...
2995,0.653846,0.004286,0.766234,0.001635,0.002172,0.002571
2996,0.846154,0.004286,0.532468,0.001901,0.001566,0.005773
2997,0.961538,0.004286,0.844156,0.007818,0.006719,0.000631
2998,0.423077,0.042857,0.818182,0.005518,0.005621,0.003810
2999,0.769231,0.010000,0.714286,0.004171,0.003858,0.002348

In [72]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.neighbors import KNeighborsRegressor

X_train, X_valid, y_train, y_valid = train_test_split(scaled_X, y, test_size = 0.8, random_state=42)

model = KNeighborsRegressor()
model.fit(X_train, y_train)
y_preds = model.predict(X_valid)
r2_score(y_preds, y_valid)

-1.239827111417434

In [73]:
final_preds = model.predict(scaled_X_final)

In [74]:
subtask2 = pd.DataFrame({"subtaskID":2, "datapointID": df_test.AppID, "answer":final_preds})

submission = pd.concat([subtask1, subtask2])
submission.to_csv("sub.csv")
submission

     subtaskID  datapointID     answer
0            1       636230   10000.00
1            1       256460  150000.00
2            1       327890  750000.00
3            1       287020   75000.00
4            1        25980  350000.00
..         ...          ...        ...
595          2       269650      10.19
596          2       261900      11.19
597          2       209630      10.24
598          2       578650      22.19
599          2      1122120      17.49

[1200 rows x 3 columns]