In [13]:
import random
import numpy as np
import torch
import os

def seed_everything(seed=20260322):
 random.seed(seed)
 os.environ['PYTHONHASHSEED'] = str(seed)
 np.random.seed(seed)

 try:
     torch.manual_seed(seed)
     torch.cuda.manual_seed(seed)
     torch.cuda.manual_seed_all(seed)
     torch.backends.cudnn.deterministic = True
     torch.backends.cudnn.benchmark = False
 except NameError:
     pass

seed_everything(20260322)

In [14]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_train.head()

,datapointID,subtaskID,Angular_Velocity_rad_s,Magnetic_Moment_Am2,Plate_Resonance_Hz,Precession_Angle_deg,Friction_Coefficient,Gravity_Vector_x,Gravity_Vector_y,Acoustic_Amplitude_dB,Tuning_Fork_Mass_g,Top_Inertia_Tensor_zz,Surface_Roughness_um,Release_Height_mm,Temperature_C,Magnetic_Field_Gradient_Tm,Target
0,query_000001,2,529.918095,NaN,9358.788710,6.254506,0.024204,0.000006,NaN,77.460356,47.670326,0.005070,3.786933,12.215896,34.686627,0.032404,1
1,query_000002,1,487.983777,4.915651,1258.815856,73.492362,0.056090,0.000006,NaN,104.739862,38.141021,0.008277,1.134007,62.917719,17.007986,0.265601,0
2,query_000003,1,345.098681,4.003950,8425.561454,31.033230,0.020378,0.000017,0.000009,63.398335,10.554692,0.003156,4.746432,14.622118,26.484398,0.921370,1
3,query_000004,2,970.950336,1.705413,7237.791779,78.983339,0.030368,-0.000011,-0.000004,117.176599,NaN,0.001690,4.887774,34.292051,34.735585,0.161256,0
4,query_000005,1,434.209023,5.004653,2956.426030,73.707073,0.026598,-0.000010,NaN,83.423059,13.455643,0.003174,0.785392,58.333491,33.389646,0.028310,0

In [15]:
df_train1 = df_train[df_train.subtaskID == 1]
df_train2 = df_train[df_train.subtaskID == 2]

df_test1 = df_test[df_test.subtaskID == 1]
df_test2 = df_test[df_test.subtaskID == 2]

df_train1.head()

,datapointID,subtaskID,Angular_Velocity_rad_s,Magnetic_Moment_Am2,Plate_Resonance_Hz,Precession_Angle_deg,Friction_Coefficient,Gravity_Vector_x,Gravity_Vector_y,Acoustic_Amplitude_dB,Tuning_Fork_Mass_g,Top_Inertia_Tensor_zz,Surface_Roughness_um,Release_Height_mm,Temperature_C,Magnetic_Field_Gradient_Tm,Target
1,query_000002,1,487.983777,4.915651,1258.815856,73.492362,0.056090,0.000006,NaN,104.739862,38.141021,0.008277,1.134007,62.917719,17.007986,0.265601,0
2,query_000003,1,345.098681,4.003950,8425.561454,31.033230,0.020378,0.000017,0.000009,63.398335,10.554692,0.003156,4.746432,14.622118,26.484398,0.921370,1
4,query_000005,1,434.209023,5.004653,2956.426030,73.707073,0.026598,-0.000010,NaN,83.423059,13.455643,0.003174,0.785392,58.333491,33.389646,0.028310,0
5,query_000006,1,216.461224,9.538866,6530.060172,8.899254,0.065165,-0.000017,0.000004,107.516402,28.572993,0.003635,2.928084,53.600840,31.781668,0.191689,0
8,query_000009,1,989.952755,3.693870,5357.537582,61.951786,0.032595,0.000008,0.000009,55.038142,45.686081,0.000703,0.702708,78.048056,15.907207,0.332296,0

In [16]:
df_test.columns

Index(['datapointID', 'subtaskID', 'Angular_Velocity_rad_s',
       'Magnetic_Moment_Am2', 'Plate_Resonance_Hz', 'Precession_Angle_deg',
       'Friction_Coefficient', 'Gravity_Vector_x', 'Gravity_Vector_y',
       'Acoustic_Amplitude_dB', 'Tuning_Fork_Mass_g', 'Top_Inertia_Tensor_zz',
       'Surface_Roughness_um', 'Release_Height_mm', 'Temperature_C',
       'Magnetic_Field_Gradient_Tm'],
      dtype='object')

In [17]:
features = [col for col in df_test.columns if col != 'datapointID' and col != 'subtaskID']
target = 'Target'

X1 = df_train1[features]
X2 = df_train2[features]

y1 = df_train1[target]
y2 = df_train2[target]

X1_final = df_test1[features]
X2_final = df_test2[features]

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
X1 = pd.DataFrame(imputer.fit_transform(X1), columns=features)
X1_final = pd.DataFrame(imputer.transform(X1_final), columns=features)

imputer = SimpleImputer(strategy='mean')
X2 = pd.DataFrame(imputer.fit_transform(X2), columns=features)
X2_final = pd.DataFrame(imputer.transform(X2_final), columns=features)

X1.head()

,Angular_Velocity_rad_s,Magnetic_Moment_Am2,Plate_Resonance_Hz,Precession_Angle_deg,Friction_Coefficient,Gravity_Vector_x,Gravity_Vector_y,Acoustic_Amplitude_dB,Tuning_Fork_Mass_g,Top_Inertia_Tensor_zz,Surface_Roughness_um,Release_Height_mm,Temperature_C,Magnetic_Field_Gradient_Tm
0,487.983777,4.915651,1258.815856,73.492362,0.056090,0.000006,-3.144171e-08,104.739862,38.141021,0.008277,1.134007,62.917719,17.007986,0.265601
1,345.098681,4.003950,8425.561454,31.033230,0.020378,0.000017,8.631536e-06,63.398335,10.554692,0.003156,4.746432,14.622118,26.484398,0.921370
2,434.209023,5.004653,2956.426030,73.707073,0.026598,-0.000010,-3.144171e-08,83.423059,13.455643,0.003174,0.785392,58.333491,33.389646,0.028310
3,216.461224,9.538866,6530.060172,8.899254,0.065165,-0.000017,4.484924e-06,107.516402,28.572993,0.003635,2.928084,53.600840,31.781668,0.191689
4,989.952755,3.693870,5357.537582,61.951786,0.032595,0.000008,9.249371e-06,55.038142,45.686081,0.000703,0.702708,78.048056,15.907207,0.332296

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from lightgbm import LGBMClassifier
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

estimators = [
    ('gb', LGBMClassifier(verbose=0)),
    ('svm', make_pipeline(StandardScaler(), LinearSVC()))]
model2 = StackingClassifier(estimators=estimators, final_estimator=LinearSVC())

model1 = LGBMClassifier(verbose=-1)
#model2 = LGBMClassifier(verbose=0)

print('Subtask 1: ', cross_val_score(model1, X1, y1, cv=3, scoring='f1_macro').mean())
print('Subtask 2: ',cross_val_score(model2, X2, y2, cv=3, scoring='f1_macro').mean())

Subtask 1:  0.8916974103328686
Subtask 2:  0.7337532552699999

In [29]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform

distributions = {
    "num_leaves": [30, 40, 50, 60, 70, 80, 100],
    "max_depth": [2, 3, 4, 5, 6, 7, 8],
    "learning_rate": uniform(0.01, 0.1),
    "n_estimators": [50, 100, 200, 300, 400, 500, 750],
    "min_child_samples": [10, 20, 30, 40, 50, 60, 70]
}
clf = RandomizedSearchCV(model1, distributions)
search = clf.fit(X1, y1)
search.best_params_

{'learning_rate': 0.059297493458401226,
 'max_depth': 4,
 'min_child_samples': 50,
 'n_estimators': 300,
 'num_leaves': 70}

In [30]:
model1 = LGBMClassifier(verbose=-1, **search.best_params_)
#model2 = LGBMClassifier(verbose=0)

print('Subtask 1: ', cross_val_score(model1, X1, y1, cv=3, scoring='f1_macro').mean())
print('Subtask 2: ',cross_val_score(model2, X2, y2, cv=3, scoring='f1_macro').mean())

Subtask 1:  0.8921939082513757
Subtask 2:  0.7337532552699999

In [31]:
model1.fit(X1, y1)
preds_1 = model1.predict(X1_final)

model2.fit(X2, y2)
preds_2 = model2.predict(X2_final)

In [32]:
df_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test1.datapointID,
    "answer": preds_1
})

df_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test2.datapointID,
    "answer": preds_2
})

df_1.head()

   subtaskID   datapointID  answer
0          1  query_100001       0
1          1  query_100002       0
3          1  query_100004       0
5          1  query_100006       1
6          1  query_100007       0

In [33]:
submission = pd.concat([df_1, df_2])
submission

       subtaskID   datapointID  answer
0              1  query_100001       0
1              1  query_100002       0
3              1  query_100004       0
5              1  query_100006       1
6              1  query_100007       0
...          ...           ...     ...
29992          2  query_129993       1
29993          2  query_129994       0
29995          2  query_129996       0
29997          2  query_129998       1
29998          2  query_129999       1

[30000 rows x 3 columns]

In [34]:
submission.to_csv("submission.csv", index=False)