In [148]:
import pandas as pd

df_train = pd.read_csv("train_data.csv")
df_test = pd.read_csv("test_data.csv")

df_test.head()

,ID,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,smokes,gender
0,1861,43,166,54,67.9,110.9,6.9,5.91,1.80,no,F
1,354,38,198,55,74.4,123.5,8.2,4.43,1.15,yes,M
2,1334,20,198,69,64.1,92.9,7.5,8.15,3.48,0,F
3,906,45,169,85,76.2,90.0,5.7,9.75,1.76,no,F
4,1290,22,196,83,73.9,118.6,8.5,1.59,1.62,1,F

In [149]:
#subtask 1

answers = []

for _, row in df_test.iterrows():
    BMI = row.weight_kg / ((row.height_cm/100)**2)
    if BMI > 25:
        answers.append(1)
    else:
        answers.append(0)

subtask_1 = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test.ID,
    "answer": answers
})

subtask_1.head()

   subtaskID  datapointID  answer
0          1         1861       0
1          1          354       0
2          1         1334       0
3          1          906       1
4          1         1290       0

In [150]:
#preprocessing

df_train.smokes = df_train.smokes.map({"yes": 1, "no": 0, "0": 0, "1": 1})
df_train.gender = df_train.gender.map({"M": 0, "F": 1})

df_test.smokes = df_test.smokes.map({"yes": 1, "no": 0, "0": 0, "1": 1})
df_test.gender = df_test.gender.map({"M": 0, "F": 1})

df_train.sleep_hours = df_train.sleep_hours.fillna(df_train.sleep_hours.mean())
df_test.sleep_hours = df_test.sleep_hours.fillna(df_test.sleep_hours.mean())

df_test.head()

,ID,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,smokes,gender
0,1861,43,166,54,67.9,110.9,6.9,5.91,1.80,0,1
1,354,38,198,55,74.4,123.5,8.2,4.43,1.15,1,0
2,1334,20,198,69,64.1,92.9,7.5,8.15,3.48,0,1
3,906,45,169,85,76.2,90.0,5.7,9.75,1.76,0,1
4,1290,22,196,83,73.9,118.6,8.5,1.59,1.62,1,1

In [151]:
#scaling

features = ['age', 'height_cm', 'weight_kg', 'heart_rate', 'blood_pressure', 'sleep_hours', 'nutrition_quality', 'activity_index', 'smokes', 'gender']
target = 'is_fit'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=features)
X_final = pd.DataFrame(scaler.transform(X_final), columns=features)

X.head()

,age,height_cm,weight_kg,heart_rate,blood_pressure,sleep_hours,nutrition_quality,activity_index,smokes,gender
0,-0.790338,0.170541,-1.055566,-0.580545,-0.467235,0.689107,-1.713799,-1.164068,-0.894301,-1.013846
1,-0.846082,0.871272,-0.476830,0.426115,-0.405307,-0.623035,-1.182755,-1.641242,-0.894301,0.986343
2,0.993454,-1.160850,0.680642,0.500990,-0.460354,0.412866,-1.263111,-1.623569,1.118191,0.986343
3,1.495145,1.642077,-0.862654,-2.111334,0.296545,0.067566,-1.043007,-0.731076,-0.894301,0.986343
4,-0.232903,-1.300996,1.066466,-0.056417,-0.253927,0.896287,1.210434,-0.934317,1.118191,-1.013846

In [152]:
#splitting the data

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, stratify=y, random_state=42)

In [153]:
#training and predicting

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import f1_score

model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)
y_preds = model.predict(X_test)
f1_score(y_preds, y_test)

0.7131782945736435

In [154]:
y_final = model.predict(X_final)

In [155]:
subtask_2 = pd.DataFrame({
    "subtaskID": 2,
    "datapointID": df_test.ID,
    "answer": y_final
})

submission = pd.concat([subtask_1, subtask_2])

submission.to_csv("submission.csv")

In [156]:
submission

     subtaskID  datapointID  answer
0            1         1861       0
1            1          354       0
2            1         1334       0
3            1          906       1
4            1         1290       0
..         ...          ...     ...
395          2          966       0
396          2         1285       0
397          2         1740       1
398          2          262       0
399          2          536       0

[800 rows x 3 columns]