In [22]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,id_hex,flux_energy,resonance_str,sensor_x,sensor_y
0,2E86E,17835.148887,gardsolidverianluxhelidluxlum,-30.140797,20.628435
1,A5890,20479.820172,echofailfailkzzvoidkzzbzzfailerrnu,36.334533,-21.720997
2,49392,7801.324247,aetaetidaetluzmianaetianver,-14.463592,19.667346
3,5C0D4,11359.735179,failzecho,-9.244456,32.596626
4,E1069,26632.889062,verianobsid,-0.008725,-44.631826

In [23]:
def is_prime(x):
    if x <= 1:
        return False
    if x == 2:
        return True
    if x % 2 == 0:
        return False
    for d in range(2, x//2):
        if x%d==0:
            return False
    return True

is_prime(11)

True

In [24]:
preds = df_test.resonance_str.str.len().apply(is_prime)
preds

0       False
1        True
2        True
3        True
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999     True
Name: resonance_str, Length: 3000, dtype: bool

In [25]:
preds.value_counts()

resonance_str
True     1812
False    1188
Name: count, dtype: int64

In [26]:
submission = pd.DataFrame({
    "subtaskID": 1,
    "datapointID": df_test.id_hex,
    "answer": [int(pred) for pred in preds]
})

submission

      subtaskID datapointID  answer
0             1        CE15       0
1             1       F0FD5       1
2             1       C1984       1
3             1        AA7D       1
4             1       64091       0
...         ...         ...     ...
2995          1       E23C1       0
2996          1       23A8A       0
2997          1       A9650       0
2998          1       EA2D6       0
2999          1       54AA6       1

[3000 rows x 3 columns]

In [27]:
submission.to_csv("submission.csv", index=False)