In [129]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,SampleID,humidity,wind_speed,pressure,rainfall,cloud_cover,solar_radiation,day_of_year,temperature
0,1,52.472407,20.944851,1005.553988,5.190818,26.170568,679.263245,313,5.33
1,2,87.042858,16.082891,1016.257028,4.791819,24.697880,635.169456,328,3.43
2,3,73.919637,9.285828,1026.188375,0.256421,90.625458,501.470266,7,-1.81
3,4,65.919509,24.413851,1021.966747,3.412478,24.954620,769.233001,206,24.23
4,5,39.361118,20.541935,1024.196834,3.801956,27.194973,240.332161,114,13.53

In [130]:
df_train.columns

Index(['SampleID', 'humidity', 'wind_speed', 'pressure', 'rainfall',
       'cloud_cover', 'solar_radiation', 'day_of_year', 'temperature'],
      dtype='object')

In [131]:
#preprocessing

features = ['humidity', 'wind_speed', 'pressure', 'rainfall', 'cloud_cover', 'solar_radiation', 'day_of_year']
target = 'temperature'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = pd.DataFrame(scaler.fit_transform(X), columns=features)
X_final = pd.DataFrame(scaler.transform(X_final), columns=features)

X.head()

,humidity,wind_speed,pressure,rainfall,cloud_cover,solar_radiation,day_of_year
0,-0.415636,0.758080,-1.119670,0.078840,-0.834041,1.091812,1.240930
1,1.515310,0.189844,0.081991,-0.060318,-0.885619,0.878591,1.382399
2,0.782307,-0.604555,1.197012,-1.642125,1.423390,0.232074,-1.645041
3,0.335457,1.163515,0.723038,-0.541390,-0.876627,1.526870,0.231783
4,-1.147973,0.710990,0.973416,-0.405552,-0.798162,-1.030687,-0.635894

In [132]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, random_state=42)

In [133]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import root_mean_squared_error

model = CatBoostRegressor(random_state=42)
model.fit(X, y)
y_preds = model.predict(X_valid)
root_mean_squared_error(y_valid, y_preds)

Learning rate set to 0.036696
0:	learn: 7.8642369	total: 1.52ms	remaining: 1.52s
1:	learn: 7.6716824	total: 2.63ms	remaining: 1.31s
2:	learn: 7.5010510	total: 3.71ms	remaining: 1.23s
3:	learn: 7.3141660	total: 5.6ms	remaining: 1.39s
4:	learn: 7.1583452	total: 7.3ms	remaining: 1.45s
5:	learn: 6.9842116	total: 9.2ms	remaining: 1.52s
6:	learn: 6.8102758	total: 11.5ms	remaining: 1.63s
7:	learn: 6.6639304	total: 13.3ms	remaining: 1.65s
8:	learn: 6.5263447	total: 15.3ms	remaining: 1.68s
9:	learn: 6.3658643	total: 17.5ms	remaining: 1.74s
10:	learn: 6.2044734	total: 19.3ms	remaining: 1.74s
11:	learn: 6.0559393	total: 21.4ms	remaining: 1.76s
12:	learn: 5.9180890	total: 23.6ms	remaining: 1.79s
13:	learn: 5.7828931	total: 25.4ms	remaining: 1.79s
14:	learn: 5.6727254	total: 28.2ms	remaining: 1.85s
15:	learn: 5.5568371	total: 30.2ms	remaining: 1.86s
16:	learn: 5.4300712	total: 32.2ms	remaining: 1.86s
17:	learn: 5.3092134	total: 34.1ms	remaining: 1.86s
18:	learn: 5.1895926	total: 36.3ms	remaining: 1.87s
19:	learn: 5.0840146	total: 38.5ms	remaining: 1.89s
20:	learn: 4.9949418	total: 41.1ms	remaining: 1.92s
21:	learn: 4.8913986	total: 43.2ms	remaining: 1.92s
22:	learn: 4.7928164	total: 45.5ms	remaining: 1.93s
23:	learn: 4.6973990	total: 47.8ms	remaining: 1.94s
24:	learn: 4.5959354	total: 48.9ms	remaining: 1.91s
25:	learn: 4.5082137	total: 50.8ms	remaining: 1.9s
26:	learn: 4.4167358	total: 52.3ms	remaining: 1.89s
27:	learn: 4.3354762	total: 53.9ms	remaining: 1.87s
28:	learn: 4.2575302	total: 56.3ms	remaining: 1.88s
29:	learn: 4.1792443	total: 58.9ms	remaining: 1.9s
30:	learn: 4.0877447	total: 62ms	remaining: 1.94s
31:	learn: 4.0169549	total: 64.3ms	remaining: 1.95s
32:	learn: 3.9450689	total: 65.8ms	remaining: 1.93s
33:	learn: 3.8605777	total: 67.8ms	remaining: 1.93s
34:	learn: 3.7967439	total: 69.3ms	remaining: 1.91s
35:	learn: 3.7250381	total: 71.2ms	remaining: 1.91s
36:	learn: 3.6610144	total: 73.2ms	remaining: 1.9s
37:	learn: 3.6042781	total: 75.3ms	remaining: 1.91s
38:	learn: 3.5406364	total: 77.1ms	remaining: 1.9s
39:	learn: 3.4709952	total: 79ms	remaining: 1.9s
40:	learn: 3.4239518	total: 80.6ms	remaining: 1.89s
41:	learn: 3.3663419	total: 82ms	remaining: 1.87s
42:	learn: 3.3099718	total: 83.4ms	remaining: 1.86s
43:	learn: 3.2518101	total: 85.6ms	remaining: 1.86s
44:	learn: 3.2005015	total: 87ms	remaining: 1.85s
45:	learn: 3.1540709	total: 88.3ms	remaining: 1.83s
46:	learn: 3.1079721	total: 89.9ms	remaining: 1.82s
47:	learn: 3.0641704	total: 91.2ms	remaining: 1.81s
48:	learn: 3.0195531	total: 92.4ms	remaining: 1.79s
49:	learn: 2.9794184	total: 93.6ms	remaining: 1.78s
50:	learn: 2.9367077	total: 94.8ms	remaining: 1.76s
51:	learn: 2.8844020	total: 96.5ms	remaining: 1.76s
52:	learn: 2.8457201	total: 97.6ms	remaining: 1.74s
53:	learn: 2.8035390	total: 98.6ms	remaining: 1.73s
54:	learn: 2.7778654	total: 99.7ms	remaining: 1.71s
55:	learn: 2.7425536	total: 101ms	remaining: 1.71s
56:	learn: 2.7023834	total: 103ms	remaining: 1.7s
57:	learn: 2.6689035	total: 104ms	remaining: 1.69s
58:	learn: 2.6371912	total: 105ms	remaining: 1.67s
59:	learn: 2.6045500	total: 106ms	remaining: 1.66s
60:	learn: 2.5692734	total: 108ms	remaining: 1.66s
61:	learn: 2.5379104	total: 109ms	remaining: 1.65s
62:	learn: 2.5029088	total: 110ms	remaining: 1.64s
63:	learn: 2.4708195	total: 112ms	remaining: 1.64s
64:	learn: 2.4350899	total: 114ms	remaining: 1.63s
65:	learn: 2.4089619	total: 115ms	remaining: 1.62s
66:	learn: 2.3829340	total: 116ms	remaining: 1.62s
67:	learn: 2.3650337	total: 118ms	remaining: 1.61s
68:	learn: 2.3371891	total: 119ms	remaining: 1.61s
69:	learn: 2.3134036	total: 120ms	remaining: 1.6s
70:	learn: 2.2870664	total: 122ms	remaining: 1.59s
71:	learn: 2.2679698	total: 123ms	remaining: 1.58s
72:	learn: 2.2411941	total: 125ms	remaining: 1.58s
73:	learn: 2.2160047	total: 126ms	remaining: 1.58s
74:	learn: 2.1951041	total: 128ms	remaining: 1.57s
75:	learn: 2.1768003	total: 130ms	remaining: 1.57s
76:	learn: 2.1486993	total: 131ms	remaining: 1.57s
77:	learn: 2.1247865	total: 133ms	remaining: 1.57s
78:	learn: 2.1051328	total: 135ms	remaining: 1.57s
79:	learn: 2.0914089	total: 137ms	remaining: 1.58s
80:	learn: 2.0712751	total: 139ms	remaining: 1.57s
81:	learn: 2.0494309	total: 140ms	remaining: 1.56s
82:	learn: 2.0314185	total: 142ms	remaining: 1.56s
83:	learn: 2.0097641	total: 143ms	remaining: 1.56s
84:	learn: 1.9911575	total: 144ms	remaining: 1.55s
85:	learn: 1.9792484	total: 145ms	remaining: 1.54s
86:	learn: 1.9615984	total: 147ms	remaining: 1.54s
87:	learn: 1.9434133	total: 148ms	remaining: 1.54s
88:	learn: 1.9310311	total: 149ms	remaining: 1.53s
89:	learn: 1.9122481	total: 150ms	remaining: 1.52s
90:	learn: 1.8990997	total: 152ms	remaining: 1.52s
91:	learn: 1.8841145	total: 153ms	remaining: 1.51s
92:	learn: 1.8695082	total: 154ms	remaining: 1.51s
93:	learn: 1.8589353	total: 155ms	remaining: 1.5s
94:	learn: 1.8471475	total: 156ms	remaining: 1.49s
95:	learn: 1.8301038	total: 158ms	remaining: 1.49s
96:	learn: 1.8194048	total: 159ms	remaining: 1.48s
97:	learn: 1.8078182	total: 160ms	remaining: 1.47s
98:	learn: 1.7916988	total: 161ms	remaining: 1.46s
99:	learn: 1.7815815	total: 162ms	remaining: 1.46s
100:	learn: 1.7682727	total: 163ms	remaining: 1.45s
101:	learn: 1.7577479	total: 165ms	remaining: 1.46s
102:	learn: 1.7453018	total: 167ms	remaining: 1.45s
103:	learn: 1.7355021	total: 168ms	remaining: 1.44s
104:	learn: 1.7236082	total: 169ms	remaining: 1.44s
105:	learn: 1.7113439	total: 171ms	remaining: 1.44s
106:	learn: 1.7026665	total: 172ms	remaining: 1.43s
107:	learn: 1.6886871	total: 173ms	remaining: 1.43s
108:	learn: 1.6796389	total: 175ms	remaining: 1.43s
109:	learn: 1.6675941	total: 177ms	remaining: 1.43s
110:	learn: 1.6563544	total: 178ms	remaining: 1.43s
111:	learn: 1.6440877	total: 180ms	remaining: 1.43s
112:	learn: 1.6350969	total: 181ms	remaining: 1.42s
113:	learn: 1.6228895	total: 182ms	remaining: 1.42s
114:	learn: 1.6143069	total: 183ms	remaining: 1.41s
115:	learn: 1.6052176	total: 184ms	remaining: 1.4s
116:	learn: 1.5954322	total: 186ms	remaining: 1.4s
117:	learn: 1.5883715	total: 187ms	remaining: 1.4s
118:	learn: 1.5808110	total: 188ms	remaining: 1.39s
119:	learn: 1.5705612	total: 189ms	remaining: 1.38s
120:	learn: 1.5597763	total: 190ms	remaining: 1.38s
121:	learn: 1.5537158	total: 192ms	remaining: 1.38s
122:	learn: 1.5446087	total: 193ms	remaining: 1.37s
123:	learn: 1.5383409	total: 194ms	remaining: 1.37s
124:	learn: 1.5315213	total: 195ms	remaining: 1.36s
125:	learn: 1.5228371	total: 196ms	remaining: 1.36s
126:	learn: 1.5175905	total: 198ms	remaining: 1.36s
127:	learn: 1.5116284	total: 199ms	remaining: 1.35s
128:	learn: 1.5050723	total: 200ms	remaining: 1.35s
129:	learn: 1.4965798	total: 201ms	remaining: 1.35s
130:	learn: 1.4896712	total: 203ms	remaining: 1.34s
131:	learn: 1.4839017	total: 204ms	remaining: 1.34s
132:	learn: 1.4764304	total: 205ms	remaining: 1.34s
133:	learn: 1.4691305	total: 206ms	remaining: 1.33s
134:	learn: 1.4634790	total: 207ms	remaining: 1.33s
135:	learn: 1.4573603	total: 209ms	remaining: 1.33s
136:	learn: 1.4494921	total: 210ms	remaining: 1.32s
137:	learn: 1.4439979	total: 211ms	remaining: 1.32s
138:	learn: 1.4382489	total: 213ms	remaining: 1.32s
139:	learn: 1.4333077	total: 215ms	remaining: 1.32s
140:	learn: 1.4250866	total: 216ms	remaining: 1.32s
141:	learn: 1.4190505	total: 217ms	remaining: 1.31s
142:	learn: 1.4144210	total: 218ms	remaining: 1.31s
143:	learn: 1.4082687	total: 220ms	remaining: 1.31s
144:	learn: 1.4021686	total: 222ms	remaining: 1.31s
145:	learn: 1.3952975	total: 223ms	remaining: 1.3s
146:	learn: 1.3894452	total: 224ms	remaining: 1.3s
147:	learn: 1.3828199	total: 225ms	remaining: 1.3s
148:	learn: 1.3786758	total: 227ms	remaining: 1.29s
149:	learn: 1.3733917	total: 228ms	remaining: 1.29s
150:	learn: 1.3686750	total: 229ms	remaining: 1.29s
151:	learn: 1.3627482	total: 231ms	remaining: 1.29s
152:	learn: 1.3573501	total: 232ms	remaining: 1.29s
153:	learn: 1.3501361	total: 233ms	remaining: 1.28s
154:	learn: 1.3438869	total: 234ms	remaining: 1.28s
155:	learn: 1.3389323	total: 235ms	remaining: 1.27s
156:	learn: 1.3340133	total: 237ms	remaining: 1.27s
157:	learn: 1.3299493	total: 238ms	remaining: 1.27s
158:	learn: 1.3261135	total: 239ms	remaining: 1.26s
159:	learn: 1.3223441	total: 240ms	remaining: 1.26s
160:	learn: 1.3179037	total: 242ms	remaining: 1.26s
161:	learn: 1.3129706	total: 244ms	remaining: 1.26s
162:	learn: 1.3066138	total: 245ms	remaining: 1.26s
163:	learn: 1.3004742	total: 247ms	remaining: 1.26s
164:	learn: 1.2957284	total: 249ms	remaining: 1.26s
165:	learn: 1.2916200	total: 250ms	remaining: 1.25s
166:	learn: 1.2882022	total: 251ms	remaining: 1.25s
167:	learn: 1.2841190	total: 252ms	remaining: 1.25s
168:	learn: 1.2803639	total: 253ms	remaining: 1.25s
169:	learn: 1.2770220	total: 255ms	remaining: 1.24s
170:	learn: 1.2726536	total: 256ms	remaining: 1.24s
171:	learn: 1.2679208	total: 257ms	remaining: 1.23s
172:	learn: 1.2640021	total: 257ms	remaining: 1.23s
173:	learn: 1.2606368	total: 259ms	remaining: 1.23s
174:	learn: 1.2556950	total: 260ms	remaining: 1.23s
175:	learn: 1.2529476	total: 261ms	remaining: 1.22s
176:	learn: 1.2474960	total: 262ms	remaining: 1.22s
177:	learn: 1.2422378	total: 263ms	remaining: 1.21s
178:	learn: 1.2396399	total: 264ms	remaining: 1.21s
179:	learn: 1.2365938	total: 265ms	remaining: 1.21s
180:	learn: 1.2321492	total: 266ms	remaining: 1.21s
181:	learn: 1.2272891	total: 267ms	remaining: 1.2s
182:	learn: 1.2229190	total: 268ms	remaining: 1.2s
183:	learn: 1.2192582	total: 269ms	remaining: 1.19s
184:	learn: 1.2152557	total: 271ms	remaining: 1.19s
185:	learn: 1.2121858	total: 272ms	remaining: 1.19s
186:	learn: 1.2094595	total: 273ms	remaining: 1.19s
187:	learn: 1.2041770	total: 274ms	remaining: 1.18s
188:	learn: 1.2009854	total: 275ms	remaining: 1.18s
189:	learn: 1.1964511	total: 276ms	remaining: 1.18s
190:	learn: 1.1921231	total: 277ms	remaining: 1.17s
191:	learn: 1.1886817	total: 278ms	remaining: 1.17s
192:	learn: 1.1850304	total: 279ms	remaining: 1.17s
193:	learn: 1.1818091	total: 280ms	remaining: 1.16s
194:	learn: 1.1785332	total: 281ms	remaining: 1.16s
195:	learn: 1.1762108	total: 283ms	remaining: 1.16s
196:	learn: 1.1724544	total: 284ms	remaining: 1.16s
197:	learn: 1.1701702	total: 285ms	remaining: 1.15s
198:	learn: 1.1674438	total: 286ms	remaining: 1.15s
199:	learn: 1.1650918	total: 287ms	remaining: 1.15s
200:	learn: 1.1628953	total: 288ms	remaining: 1.15s
201:	learn: 1.1585358	total: 289ms	remaining: 1.14s
202:	learn: 1.1566441	total: 290ms	remaining: 1.14s
203:	learn: 1.1537460	total: 291ms	remaining: 1.14s
204:	learn: 1.1491454	total: 292ms	remaining: 1.13s
205:	learn: 1.1464191	total: 293ms	remaining: 1.13s
206:	learn: 1.1417174	total: 295ms	remaining: 1.13s
207:	learn: 1.1390155	total: 296ms	remaining: 1.13s
208:	learn: 1.1365853	total: 297ms	remaining: 1.12s
209:	learn: 1.1339498	total: 298ms	remaining: 1.12s
210:	learn: 1.1311480	total: 299ms	remaining: 1.12s
211:	learn: 1.1267896	total: 300ms	remaining: 1.11s
212:	learn: 1.1220692	total: 301ms	remaining: 1.11s
213:	learn: 1.1188207	total: 302ms	remaining: 1.11s
214:	learn: 1.1152786	total: 303ms	remaining: 1.1s
215:	learn: 1.1127418	total: 304ms	remaining: 1.1s
216:	learn: 1.1098914	total: 305ms	remaining: 1.1s
217:	learn: 1.1080976	total: 306ms	remaining: 1.1s
218:	learn: 1.1056313	total: 307ms	remaining: 1.09s
219:	learn: 1.1019044	total: 308ms	remaining: 1.09s
220:	learn: 1.0986672	total: 309ms	remaining: 1.09s
221:	learn: 1.0954880	total: 310ms	remaining: 1.09s
222:	learn: 1.0930989	total: 312ms	remaining: 1.09s
223:	learn: 1.0913928	total: 313ms	remaining: 1.08s
224:	learn: 1.0891223	total: 314ms	remaining: 1.08s
225:	learn: 1.0865297	total: 315ms	remaining: 1.08s
226:	learn: 1.0839846	total: 316ms	remaining: 1.07s
227:	learn: 1.0794573	total: 317ms	remaining: 1.07s
228:	learn: 1.0758793	total: 318ms	remaining: 1.07s
229:	learn: 1.0723946	total: 319ms	remaining: 1.07s
230:	learn: 1.0695780	total: 320ms	remaining: 1.06s
231:	learn: 1.0673463	total: 321ms	remaining: 1.06s
232:	learn: 1.0657032	total: 322ms	remaining: 1.06s
233:	learn: 1.0632370	total: 323ms	remaining: 1.06s
234:	learn: 1.0595545	total: 324ms	remaining: 1.05s
235:	learn: 1.0575531	total: 325ms	remaining: 1.05s
236:	learn: 1.0553733	total: 326ms	remaining: 1.05s
237:	learn: 1.0535067	total: 327ms	remaining: 1.05s
238:	learn: 1.0518195	total: 329ms	remaining: 1.05s
239:	learn: 1.0493916	total: 329ms	remaining: 1.04s
240:	learn: 1.0467047	total: 330ms	remaining: 1.04s
241:	learn: 1.0425894	total: 331ms	remaining: 1.04s
242:	learn: 1.0387417	total: 333ms	remaining: 1.04s
243:	learn: 1.0365076	total: 335ms	remaining: 1.04s
244:	learn: 1.0336496	total: 336ms	remaining: 1.04s
245:	learn: 1.0309662	total: 338ms	remaining: 1.03s
246:	learn: 1.0298186	total: 339ms	remaining: 1.03s
247:	learn: 1.0266791	total: 340ms	remaining: 1.03s
248:	learn: 1.0249593	total: 341ms	remaining: 1.03s
249:	learn: 1.0221505	total: 343ms	remaining: 1.03s
250:	learn: 1.0191292	total: 344ms	remaining: 1.03s
251:	learn: 1.0170814	total: 346ms	remaining: 1.02s
252:	learn: 1.0140199	total: 347ms	remaining: 1.02s
253:	learn: 1.0120396	total: 349ms	remaining: 1.02s
254:	learn: 1.0099136	total: 350ms	remaining: 1.02s
255:	learn: 1.0077933	total: 351ms	remaining: 1.02s
256:	learn: 1.0046219	total: 353ms	remaining: 1.02s
257:	learn: 1.0028594	total: 353ms	remaining: 1.02s
258:	learn: 1.0013971	total: 354ms	remaining: 1.01s
259:	learn: 0.9998227	total: 356ms	remaining: 1.01s
260:	learn: 0.9973295	total: 357ms	remaining: 1.01s
261:	learn: 0.9965536	total: 358ms	remaining: 1.01s
262:	learn: 0.9943772	total: 359ms	remaining: 1.01s
263:	learn: 0.9911150	total: 360ms	remaining: 1s
264:	learn: 0.9887964	total: 362ms	remaining: 1s
265:	learn: 0.9875285	total: 363ms	remaining: 1s
266:	learn: 0.9843702	total: 364ms	remaining: 998ms
267:	learn: 0.9813495	total: 365ms	remaining: 996ms
268:	learn: 0.9797400	total: 366ms	remaining: 994ms
269:	learn: 0.9779860	total: 367ms	remaining: 992ms
270:	learn: 0.9757158	total: 368ms	remaining: 990ms
271:	learn: 0.9740647	total: 369ms	remaining: 988ms
272:	learn: 0.9708122	total: 370ms	remaining: 985ms
273:	learn: 0.9676861	total: 371ms	remaining: 983ms
274:	learn: 0.9661373	total: 372ms	remaining: 981ms
275:	learn: 0.9644943	total: 374ms	remaining: 980ms
276:	learn: 0.9630870	total: 375ms	remaining: 978ms
277:	learn: 0.9608021	total: 376ms	remaining: 976ms
278:	learn: 0.9581676	total: 377ms	remaining: 974ms
279:	learn: 0.9560573	total: 379ms	remaining: 973ms
280:	learn: 0.9547646	total: 380ms	remaining: 972ms
281:	learn: 0.9529623	total: 381ms	remaining: 970ms
282:	learn: 0.9512719	total: 382ms	remaining: 968ms
283:	learn: 0.9493958	total: 384ms	remaining: 967ms
284:	learn: 0.9475569	total: 385ms	remaining: 966ms
285:	learn: 0.9459432	total: 387ms	remaining: 965ms
286:	learn: 0.9454692	total: 387ms	remaining: 963ms
287:	learn: 0.9428233	total: 389ms	remaining: 961ms
288:	learn: 0.9422191	total: 390ms	remaining: 960ms
289:	learn: 0.9399580	total: 391ms	remaining: 958ms
290:	learn: 0.9389901	total: 393ms	remaining: 957ms
291:	learn: 0.9379485	total: 395ms	remaining: 957ms
292:	learn: 0.9366393	total: 396ms	remaining: 955ms
293:	learn: 0.9334394	total: 397ms	remaining: 954ms
294:	learn: 0.9307776	total: 398ms	remaining: 952ms
295:	learn: 0.9297398	total: 400ms	remaining: 951ms
296:	learn: 0.9274101	total: 401ms	remaining: 950ms
297:	learn: 0.9257490	total: 403ms	remaining: 948ms
298:	learn: 0.9250282	total: 404ms	remaining: 946ms
299:	learn: 0.9216727	total: 405ms	remaining: 944ms
300:	learn: 0.9207934	total: 406ms	remaining: 944ms
301:	learn: 0.9199536	total: 408ms	remaining: 942ms
302:	learn: 0.9189178	total: 409ms	remaining: 940ms
303:	learn: 0.9183221	total: 410ms	remaining: 938ms
304:	learn: 0.9156753	total: 411ms	remaining: 936ms
305:	learn: 0.9144426	total: 412ms	remaining: 935ms
306:	learn: 0.9114776	total: 413ms	remaining: 933ms
307:	learn: 0.9091696	total: 414ms	remaining: 931ms
308:	learn: 0.9081437	total: 415ms	remaining: 929ms
309:	learn: 0.9068510	total: 416ms	remaining: 927ms
310:	learn: 0.9057961	total: 418ms	remaining: 926ms
311:	learn: 0.9021963	total: 419ms	remaining: 924ms
312:	learn: 0.9009151	total: 420ms	remaining: 923ms
313:	learn: 0.9004392	total: 422ms	remaining: 921ms
314:	learn: 0.8985178	total: 423ms	remaining: 920ms
315:	learn: 0.8981200	total: 424ms	remaining: 918ms
316:	learn: 0.8963257	total: 425ms	remaining: 916ms
317:	learn: 0.8956535	total: 426ms	remaining: 914ms
318:	learn: 0.8941754	total: 427ms	remaining: 912ms
319:	learn: 0.8932043	total: 429ms	remaining: 911ms
320:	learn: 0.8900051	total: 430ms	remaining: 909ms
321:	learn: 0.8888143	total: 431ms	remaining: 907ms
322:	learn: 0.8872688	total: 432ms	remaining: 905ms
323:	learn: 0.8869792	total: 433ms	remaining: 902ms
324:	learn: 0.8855095	total: 434ms	remaining: 901ms
325:	learn: 0.8849926	total: 435ms	remaining: 899ms
326:	learn: 0.8835474	total: 436ms	remaining: 897ms
327:	learn: 0.8815559	total: 437ms	remaining: 895ms
328:	learn: 0.8810520	total: 438ms	remaining: 893ms
329:	learn: 0.8780062	total: 439ms	remaining: 892ms
330:	learn: 0.8747331	total: 440ms	remaining: 890ms
331:	learn: 0.8733450	total: 441ms	remaining: 888ms
332:	learn: 0.8710480	total: 442ms	remaining: 886ms
333:	learn: 0.8697889	total: 443ms	remaining: 884ms
334:	learn: 0.8690239	total: 444ms	remaining: 882ms
335:	learn: 0.8671763	total: 446ms	remaining: 881ms
336:	learn: 0.8660768	total: 447ms	remaining: 879ms
337:	learn: 0.8644567	total: 448ms	remaining: 877ms
338:	learn: 0.8640645	total: 449ms	remaining: 875ms
339:	learn: 0.8634170	total: 450ms	remaining: 873ms
340:	learn: 0.8601135	total: 451ms	remaining: 872ms
341:	learn: 0.8598327	total: 452ms	remaining: 870ms
342:	learn: 0.8574367	total: 453ms	remaining: 868ms
343:	learn: 0.8567040	total: 454ms	remaining: 866ms
344:	learn: 0.8563679	total: 455ms	remaining: 864ms
345:	learn: 0.8543909	total: 457ms	remaining: 863ms
346:	learn: 0.8520792	total: 458ms	remaining: 862ms
347:	learn: 0.8516758	total: 459ms	remaining: 859ms
348:	learn: 0.8502054	total: 460ms	remaining: 857ms
349:	learn: 0.8496337	total: 461ms	remaining: 855ms
350:	learn: 0.8493174	total: 462ms	remaining: 853ms
351:	learn: 0.8489059	total: 463ms	remaining: 853ms
352:	learn: 0.8487757	total: 464ms	remaining: 851ms
353:	learn: 0.8466827	total: 465ms	remaining: 849ms
354:	learn: 0.8463811	total: 466ms	remaining: 847ms
355:	learn: 0.8456009	total: 467ms	remaining: 845ms
356:	learn: 0.8450364	total: 468ms	remaining: 843ms
357:	learn: 0.8436081	total: 470ms	remaining: 842ms
358:	learn: 0.8433112	total: 470ms	remaining: 840ms
359:	learn: 0.8411099	total: 471ms	remaining: 838ms
360:	learn: 0.8400813	total: 472ms	remaining: 836ms
361:	learn: 0.8396215	total: 474ms	remaining: 835ms
362:	learn: 0.8389496	total: 475ms	remaining: 834ms
363:	learn: 0.8376739	total: 476ms	remaining: 832ms
364:	learn: 0.8358741	total: 477ms	remaining: 830ms
365:	learn: 0.8356340	total: 478ms	remaining: 828ms
366:	learn: 0.8342192	total: 479ms	remaining: 826ms
367:	learn: 0.8323039	total: 480ms	remaining: 825ms
368:	learn: 0.8315219	total: 481ms	remaining: 823ms
369:	learn: 0.8296913	total: 482ms	remaining: 821ms
370:	learn: 0.8282219	total: 483ms	remaining: 819ms
371:	learn: 0.8259117	total: 484ms	remaining: 817ms
372:	learn: 0.8236713	total: 485ms	remaining: 816ms
373:	learn: 0.8224474	total: 486ms	remaining: 814ms
374:	learn: 0.8209094	total: 487ms	remaining: 812ms
375:	learn: 0.8197566	total: 488ms	remaining: 810ms
376:	learn: 0.8179495	total: 489ms	remaining: 808ms
377:	learn: 0.8165066	total: 491ms	remaining: 807ms
378:	learn: 0.8163304	total: 492ms	remaining: 806ms
379:	learn: 0.8161565	total: 493ms	remaining: 805ms
380:	learn: 0.8153517	total: 494ms	remaining: 803ms
381:	learn: 0.8132126	total: 495ms	remaining: 801ms
382:	learn: 0.8112253	total: 496ms	remaining: 800ms
383:	learn: 0.8108291	total: 497ms	remaining: 798ms
384:	learn: 0.8102167	total: 499ms	remaining: 796ms

0.33306052147990217

In [134]:
y_final = model.predict(X_final)

In [135]:
submission = pd.DataFrame({
    "SampleID": df_test.SampleID,
    "temperature": y_final
})

submission

     SampleID  temperature
0        1001     1.124816
1        1002     7.451463
2        1003    17.058233
3        1004    -0.943107
4        1005     5.977773
..        ...          ...
195      1196    21.644178
196      1197    13.774522
197      1198     7.011611
198      1199    -5.423066
199      1200    21.094390

[200 rows x 2 columns]

In [136]:
submission.to_csv("submission.csv", index=False)