In [1]:
import pandas as pd

df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

df_train.head()

,robot_id,arena_type,weather,difficulty,laps,avg_speed_mps,distance_m,battery_used_pct,collisions,unique_cells,...,efficiency_score,coverage_ratio,scan_turn_sync,pickup_efficiency,detour_index,safety_margin,patrol_consistency,speed_burst,risk_index,strategy_label
0,TR_0000,urban,clear,2,3,1.561222,2999.630719,72.252973,7,247.530750,...,13.290300,6.719937,33.092663,4.839689,-10.000000,10.983818,-0.176148,9.821879,7.942570,explorer
1,TR_0001,urban,clear,1,5,1.442525,3154.068573,64.676535,6,334.130274,...,26.398660,5.192224,30.436153,1.095235,-10.000000,9.600871,3.270004,9.372641,3.101063,explorer
2,TR_0002,forest,fog,3,2,1.722279,3065.318986,80.265380,12,259.159918,...,10.000000,3.762810,18.799661,0.986697,-5.754699,0.000000,-8.351089,14.195603,13.897243,sprinter
3,TR_0003,forest,fog,4,4,1.603709,3237.298212,76.131047,11,247.686196,...,10.000000,2.974647,21.146474,1.197847,-8.658303,4.695742,-0.860512,13.064054,9.994055,sprinter
4,TR_0004,urban,clear,2,4,1.806128,3730.035162,72.061673,4,279.860091,...,33.829585,6.206864,32.408799,4.544147,-7.942540,11.964464,4.821596,9.304336,1.649628,explorer

In [2]:
subtask1 = df_train.arena_type.nunique()
subtask2 = df_train.avg_speed_mps.max()
subtask3 = df_train.arena_type.mode()[0]
subtask4 = df_train.items_collected.max()

df_subtasks = pd.DataFrame({
    "robot_id": "GLOBAL",
    "subtaskID": [1, 2, 3, 4],
    "answer": [subtask1, subtask2, subtask3, subtask4]
})

df_subtasks

  robot_id  subtaskID  answer
0   GLOBAL          1       4
1   GLOBAL          2  2.6412
2   GLOBAL          3  forest
3   GLOBAL          4      22

In [6]:
dict1 = {'urban': 0, 'forest': 1, 'desert': 2, 'ice': 3}
dict2 = {'clear': 0, 'fog': 1, 'windy': 2}

df_train.arena_type = df_train.arena_type.map(dict1)
df_test.arena_type = df_test.arena_type.map(dict1)

df_train.weather = df_train.weather.map(dict2)
df_test.weather = df_test.weather.map(dict2)

df_train.head()

,robot_id,arena_type,weather,difficulty,laps,avg_speed_mps,distance_m,battery_used_pct,collisions,unique_cells,...,efficiency_score,coverage_ratio,scan_turn_sync,pickup_efficiency,detour_index,safety_margin,patrol_consistency,speed_burst,risk_index,strategy_label
0,TR_0000,0,0,2,3,1.561222,2999.630719,72.252973,7,247.530750,...,13.290300,6.719937,33.092663,4.839689,-10.000000,10.983818,-0.176148,9.821879,7.942570,explorer
1,TR_0001,0,0,1,5,1.442525,3154.068573,64.676535,6,334.130274,...,26.398660,5.192224,30.436153,1.095235,-10.000000,9.600871,3.270004,9.372641,3.101063,explorer
2,TR_0002,1,1,3,2,1.722279,3065.318986,80.265380,12,259.159918,...,10.000000,3.762810,18.799661,0.986697,-5.754699,0.000000,-8.351089,14.195603,13.897243,sprinter
3,TR_0003,1,1,4,4,1.603709,3237.298212,76.131047,11,247.686196,...,10.000000,2.974647,21.146474,1.197847,-8.658303,4.695742,-0.860512,13.064054,9.994055,sprinter
4,TR_0004,0,0,2,4,1.806128,3730.035162,72.061673,4,279.860091,...,33.829585,6.206864,32.408799,4.544147,-7.942540,11.964464,4.821596,9.304336,1.649628,explorer

In [9]:
features = [col for col in df_test.columns if col != 'robot_id']
target = 'strategy_label'

X = df_train[features]
y = df_train[target]

X_final = df_test[features]

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=features)
X_final = pd.DataFrame(scaler.transform(X_final), columns=features)

X.head()

,arena_type,weather,difficulty,laps,avg_speed_mps,distance_m,battery_used_pct,collisions,unique_cells,items_collected,...,return_time_s,efficiency_score,coverage_ratio,scan_turn_sync,pickup_efficiency,detour_index,safety_margin,patrol_consistency,speed_burst,risk_index
0,-1.158374,-0.735454,-0.585764,-0.647649,0.057166,-0.220154,0.549542,0.949671,0.587795,-0.120964,...,-0.039829,-1.136658,1.917534,1.792198,0.196509,-1.508353,0.272324,-1.252332,-0.146577,0.651606
1,-1.158374,-0.735454,-1.365051,0.933589,-0.365507,0.045362,-0.273361,0.548119,2.871498,-1.363742,...,-0.609104,-0.766868,0.620684,1.044105,-0.826871,-1.508353,-0.142481,-0.582703,-0.293803,-0.708466
2,-0.158339,0.457174,0.193523,-1.438268,0.630685,-0.107220,1.419798,2.957432,0.894466,-0.866631,...,0.046568,-1.229478,-0.592722,-2.232817,-0.856535,-0.267052,-3.022192,-2.840823,1.286798,2.324386
3,-0.158339,0.457174,0.972810,0.142970,0.208461,0.188455,0.970753,2.555880,0.591894,-0.618075,...,0.794701,-1.229478,-1.261780,-1.571937,-0.798826,-1.116049,-1.613739,-1.385312,0.915962,1.227907
4,-1.158374,-0.735454,-0.585764,0.142970,0.929267,1.035591,0.528764,-0.254986,1.440347,0.376148,...,-1.246926,-0.557241,1.481995,1.599617,0.115736,-0.906764,0.566462,-0.281209,-0.316188,-1.116201

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

model = LogisticRegression(max_iter=10000000000)

cross_val_score(model, X, y, cv=5, scoring='f1_macro').mean()

0.9455377981438607

In [11]:
model.fit(X, y)
y_preds = model.predict(X_final)

In [12]:
df_preds = pd.DataFrame({
    "robot_id": df_test.robot_id,
    "subtaskID": 5,
    "answer": y_preds
})

df_preds.head()

  robot_id  subtaskID    answer
0  TS_0000          5  guardian
1  TS_0001          5  guardian
2  TS_0002          5  explorer
3  TS_0003          5  sprinter
4  TS_0004          5  explorer

In [13]:
submission = pd.concat([df_subtasks, df_preds])
submission

    robot_id  subtaskID     answer
0     GLOBAL          1          4
1     GLOBAL          2     2.6412
2     GLOBAL          3     forest
3     GLOBAL          4         22
0    TS_0000          5   guardian
..       ...        ...        ...
395  TS_0395          5   explorer
396  TS_0396          5   explorer
397  TS_0397          5  collector
398  TS_0398          5  collector
399  TS_0399          5   guardian

[404 rows x 3 columns]

In [14]:
submission.to_csv("submission.csv", index=False)